---
title: "Dataset statistics"
output:
  html_document:
    df_print: paged
    code_folding: hide
---

## Load data

```{r message=FALSE, warning=FALSE}
library(ggplot2)
library(dplyr)
library(gt)
source("data_organization/utils.R")
options(scipen = 999)
```

```{r}
all.data <- load.all.datasets()
for(i in 1:length(all.data)) assign(names(all.data)[i], all.data[[i]])
rm(all.data)
datasets <- basename(data.dirs)

healthy.control.labels <- list("ERAWIJANTARI_GASTRIC_CANCER_2020" = "Healthy",
                               "YACHIDA_CRC_2019" = "Healthy",
                               "HE_INFANTS_MFGM_2019" = "Baseline",
                               "WANDRO_PRETERMS_2018" = "control",
                               "KIM_ADENOMAS_2020" = "Control",
                               "FRANZOSA_IBD_2019" = "Control",
                               "KOSTIC_INFANTS_DIABETES_2015" = "control",
                               "MARS_IBS_2020" = "H", 
                               "KANG_AUTISM_2017" = "Neurotypical", 
                               "JACOBS_IBD_FAMILIES_2016" = "Normal", 
                               "SINHA_CRC_2016" = 0, 
                               "iHMP_IBDMDB_2019" = "nonIBD",
                               "WANG_ESRD_2020" = "Control")
```

## Datasets statistics

```{r}
# Collect statistics
data.summary <- sapply(datasets, function(x) {
  
  # Count samples and subjects
  num.samples <- nrow(metadata[[x]])
  num.subjects <- n_distinct(metadata[[x]]$Subject)
  
  # Count controls, if relevant
  if ("Study.Group" %in% names(metadata[[x]])) {
    num.hc.samples <- 
      metadata[[x]] %>% 
      filter(Study.Group == healthy.control.labels[[x]]) %>% 
      nrow()
    num.hc.subjects <- 
      metadata[[x]] %>% 
      filter(Study.Group == healthy.control.labels[[x]]) %>% 
      pull(Subject) %>% 
      n_distinct()
  } else {
    num.hc.samples <- NA
    num.hc.subjects <- NA
  }
  
  # Other descriptive statistics
  num.study.groups <- n_distinct(metadata[[x]]$Study.Group)
  num.genera <- ncol(genera[[x]]) - 1
  num.metab.orig <- ncol(mtb[[x]]) - 1
  num.hmdb <-
    mtb.map[[x]] %>% 
    filter(!is.na(HMDB)) %>% 
    pull(HMDB) %>% 
    n_distinct()
  num.kegg <- 
    mtb.map[[x]] %>% 
    filter(!is.na(KEGG)) %>% 
    pull(KEGG) %>% 
    n_distinct()
  return(c("dataset" = x,
           "num_samples" = num.samples,
           "num_samples_hc" = num.hc.samples,
           "num_subjects" = num.subjects,
           "num_subjects_hc" = num.hc.subjects,
           "is_longitudinal" = num.samples > num.subjects,
           "num_study_groups" = num.study.groups,
           "num_genera" = num.genera,
           "num_original_compounds" = num.metab.orig,
           "num_hmdb_compounds" = num.hmdb,
           "num_kegg_compounds" = num.kegg))
})

# Organize statistics in a table
data.summary <- data.frame(t(data.summary)) %>% 
  tibble::remove_rownames() %>%
  mutate(num_samples = as.numeric(num_samples)) %>%
  mutate(num_subjects = as.numeric(num_subjects)) 

# Display
data.summary %>% 
  gt() %>%
  tab_header(title = "Dataset statistics") %>%
  tab_options(
    table.font.size = "smaller",
    data_row.padding = px(3)
  ) %>%
  tab_style(
    style = list(cell_fill(color = "#F9E3D6")),
    locations = cells_body(columns = dataset)
  ) %>%
  tab_style(
    style = list(cell_fill(color = "lightgrey")),
    locations = cells_column_labels()
  ) %>%
  cols_label(
    dataset = "Dataset",
    num_samples = "No.\nsamples",
    num_samples_hc = "No. control\nsamples",
    num_subjects = "No.\nsubjects",
    num_subjects_hc = "No. control\nsubjects",
    is_longitudinal = "Longitudinal?",
    num_study_groups = "No. study\ngroups",
    num_genera = "No.\ngenera",
    num_original_compounds = "No.\noriginal\ncompounds",
    num_hmdb_compounds = "No.\nHMDB",
    num_kegg_compounds = "No.\nKEGG"
  ) %>%
  cols_align(
    align = "left"
  )
  
```

### Overview statistics

```{r}
message("This collection includes:")
message(paste("-",nrow(data.summary),"datasets"))
message(paste("-",sum(data.summary$num_subjects),"subjects"))
message(paste("-",sum(data.summary$num_samples),"samples"))
```


## Shared features

### Shared genera

```{r fig.width=6, fig.height=3.2}
genera.dataset.stats <- get.genera.dataset.stats(genera, datasets)

# We further summarize these stats to get basic statistics 
#  at the genus level (average over datasets)
genera.stats <- genera.dataset.stats %>%
  group_by(Taxon) %>%
  summarise(Taxon.Overall.Mean.Abundance = 
              weighted.mean(x = Taxon.Mean.Abundance, w = Dataset.N),
            Taxon.Overall.Perc.Non.Zero = 
              weighted.mean(x = Taxon.Perc.of.Non.Zeros, w = Dataset.N),
            N.Datasets.Including.Taxon = n(),
            .groups = "drop") %>%
  mutate(Genus.Only = gsub(".*\\;g__","g__", Taxon))

# Print/plot statistics
message(paste(nrow(genera.stats), "unique genera (or higher-level clades) were found across all datasets"))

tmp <- genera.stats %>%
  group_by(N.Datasets.Including.Taxon) %>%
  summarise(N = n(), .groups = "drop") %>%
  arrange(-N.Datasets.Including.Taxon) %>%
  mutate(cum.N = cumsum(N))

label1.x <- unlist(tmp[tmp$N.Datasets.Including.Taxon == 3, "cum.N"])
label2.x <- unlist(tmp[tmp$N.Datasets.Including.Taxon == 10, "cum.N"])
label1 <- paste(label1.x,"genera are present\nin at least 3 datasets")
label2 <- paste(label2.x,"genera are present\nin at least 10 datasets")
label.y <- max(tmp$cum.N)

ggplot(tmp, aes(x = N.Datasets.Including.Taxon, y = cum.N)) +
  geom_bar(stat="identity", color='black', 
           fill='#8CBA80') +
  theme_classic() +
  ylab("No. of genera") +
  xlab("No. of datasets") +
  scale_x_continuous(breaks=2*1:7, limits = c(NA,14.5)) +
  annotate(geom = "curve", 
           x = c(3,10),
           y = c(label1.x,label2.x)+800, 
           xend = c(3.5,10.6), 
           yend = c(0.99*label.y, 0.32*label.y), 
           color = "#7E7F9A",
           curvature = -.3, 
           arrow = arrow(length = unit(2, "mm"))) +
  annotate("text", 
           x = c(3.7, 10.8), 
           y = c(0.97*label.y, 0.3*label.y)+100, 
           label = c(label1, label2), 
           color = "#272838", 
           size = 3.45, hjust = 0) +
  annotate(geom = "point",
           x = c(3,10), 
           y = c(label1.x,label2.x)+800,
           color = "#7E7F9A", size = 2) +
  geom_text(aes(label=cum.N), vjust = -0.5, size = 2.6) +
  scale_y_continuous(limits = c(0, max(tmp$cum.N) + 7)) +
  theme(axis.title = element_text(size = 11)) 

# Clean up 
rm(label1.x, label2.x, label1, label2, label.y, tmp)
```


### Shared HMDB-identified metabolites

```{r fig.width=6, fig.height=3.2}
metabolites.per.dataset <- 
  get.metab.dataset.stats(mtb.map, datasets)

# Count for each metabolite how many datasets have it
metabolites.stats <- metabolites.per.dataset %>%
  group_by(Type, Compound) %>%
  summarise(N = n(), N.Datasets.Including.Compound = n_distinct(Dataset), .groups = "drop")

# Print statistics 
print(paste(n_distinct(metabolites.stats$Compound[metabolites.stats$Type == "HMDB"]),
            "unique HMDB compound IDs were found across all datasets"))
print(paste(n_distinct(metabolites.stats$Compound[metabolites.stats$Type == "KEGG"]),
            "unique KEGG compound IDs were found across all datasets"))

tmp <- metabolites.stats %>%
  group_by(Type, N.Datasets.Including.Compound) %>%
  summarise(N = n(), .groups = "drop") %>%
  group_by(Type) %>%
  arrange(-N.Datasets.Including.Compound) %>%
  mutate(cum.N = cumsum(N))

# Focus on HMDB
tmp <- tmp %>% filter(Type == "HMDB")

label1.x <- unlist(tmp[tmp$N.Datasets.Including.Compound == 3, "cum.N"])
label2.x <- unlist(tmp[tmp$N.Datasets.Including.Compound == 10, "cum.N"])
label1 <- paste(label1.x,"compounds (HMDB)\nare present in at least\n3 datasets")
label2 <- paste(label2.x,"compounds (HMDB)\nare present in at least\n10 datasets")
label.y <- max(tmp$cum.N)

ggplot(tmp, aes(x = N.Datasets.Including.Compound, y = cum.N)) +
  geom_bar(stat="identity", color='black', 
           fill='#FDAE6B') +
  theme_classic() +
  ylab("No. of compounds") +
  xlab("No. of datasets") +
  scale_x_continuous(breaks=2*1:7, limits = c(NA,14.5)) +
  annotate(geom = "curve", 
           x = c(3,10), 
           y = c(label1.x,label2.x)+100, 
           xend = c(3,10)+0.8, 
           yend = c(0.7*label.y, 0.5*label.y), 
           color = "#7E7F9A",
           curvature = -.3, 
           arrow = arrow(length = unit(2, "mm"))) +
  annotate("text", 
           x = c(4, 11), 
           y = c(0.7*label.y, 0.5*label.y)-30, 
           label = c(label1, label2), 
           color = "#272838", 
           size = 3.45, hjust = 0) +
  annotate(geom = "point",
           x = c(3,10), y = c(label1.x,label2.x)+100,
           color = "#7E7F9A", size = 2) +
  geom_text(aes(label=cum.N), vjust = -0.5, size = 2.6) +
  scale_y_continuous(limits = c(0, max(tmp$cum.N) + 15)) +
  theme(axis.title = element_text(size = 11))

rm(label1.x, label2.x, label1, label2, label.y, tmp)
```


